### ISSUE TITLE
Default Grafana credentials 

### ISSUE THREAD

**Issue by amartellone** [oracle-quickstart/oci-cloudnative#157]
Hi,
I have successfully completed the "complete installation" by terraform scripts. 
But I'm not able to enter into Grapana as Admin. How can I obtain the default credentials? After the installation, the logs credentials are masquerade.

Thanks for your support.

Ale

**Comment by junior** [comment]
@amartellone please refer to this page: https://oracle-quickstart.github.io/oci-cloudnative/extras/monitoring/ 

The first username is `admin` and to grab the password execute this command:

```
kubectl get secret -n mushop-utilities mushop-utils-grafana \
 -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
```

**Comment by junior** [comment]
@amartellone here a more complete answer:

The Grafana Admin Password is stored on the terraform state, shows as "<sensitive>" on the result of your `terraform apply` because is marked as `sensitive=true`.

The easy way to get this output is running the command: 
```
terraform output grafana_admin_password
```
this will show the password that you can use to access the Grafana dashboards.


The Grafana Admin Password is stored as a Kubernetes secret, so we can retrieve using Kubectl as well. For convenience, the terraform scripts generates a kubeconfig file to use with the Kubectl to access the just created cluster.

If you have Kubectl installed, you can use this command to start using the new cluster:
```
export KUBECONFIG=./generated/kubeconfig
```
Note: this assumes that you are one the .../complete/terraform folder

And then you can execute this command to grab the secret:

```
kubectl get secret -n mushop-utilities mushop-utils-grafana \
 -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
```


I've noted that you may want the easy response to just do:
```
terraform output grafana_admin_password
```

Let me know if this works for you.

**Comment by junior** [comment]
@amartellone, please, let me know if 
```
terraform output grafana_admin_password
```
Worked for you.

**Comment by amartellone** [comment]
Many thanks Adao. It works perfectly for me.

Il mar 2 giu 2020, 01:11 Adao Junior <notifications@github.com> ha scritto:

**Comment by amartellone** [comment]
The issue is resolved

**Comment by junior** [comment]
Extra info: Grafana have been updated to 7.0.1 on both, helm charts and terraform scripts. https://github.com/oracle-quickstart/oci-cloudnative/tree/master/deploy/complete/terraform
