### ISSUE TITLE
using of exisitng resources 

### ISSUE THREAD

**Issue by narendratreddi** [oracle-quickstart/oci-cloudnative#32]
Hi,
Can i use the existing resources of compute instances for creation of this 3 tier application ?
I didnt find the option for selecting the existing instances during the deployment. please help in this regard.

Thanks,
Narendra

**Comment by junior** [comment]
Hello @narendratreddi, we didn't enabled that option on the UI, but you can extract the stack and change to a desired shape.

First download and extract the latest release [here](https://github.com/oci-quickstart/oci-cloudnative/releases/download/v1.0.2/mushop-basic-stack-v1.0.2.zip).

Then, open the just extracted file [/terraform/main.tf](https://github.com/oci-quickstart/oci-cloudnative/blob/master/deploy/basic/terraform/main.tf), go to the line [63](https://github.com/oci-quickstart/oci-cloudnative/blob/master/deploy/basic/terraform/main.tf#L63) and change to a desired shape. (e.g.: `VM.Standard.E2.1`)

> 63 instance_shape = "VM.Standard.E2.1.Micro"

Note that you may need to change the Loadbalance shape as well, as the Always Free has only one LB-micro.
To change the LoadBalance, go to line [69](https://github.com/oci-quickstart/oci-cloudnative/blob/master/deploy/basic/terraform/main.tf#L69) and change to something like `100Mbps`

> 69 lb_shape = "10Mbps-Micro"

The ATP also consumes the Always Free shape, to change to a regular ATP instance. Just open the atp.tf file and change the variable `is_free_tier` to `false`. Located on the line [14](https://github.com/oci-quickstart/oci-cloudnative/blob/master/deploy/basic/terraform/atp.tf#L14).

> 14 is_free_tier             = true


After you make the changes, zip everything and upload the new stack and terraform apply as the instructions.

> Note that you need to zip the files on the root, without the schema.yaml inside any folder, or the fields on the Resource Manager will not load correctly and you may have issues applying the new stack.

**Comment by peterj** [comment]
Should we add these instructions to the readme?

**Comment by jeevanjoseph** [comment]
I think the ask from @narendratreddi is to use a pre-created compute instance (or other resource) as opposed to creating a new one, and not changing the shapes of the resources. If that's the case, then a `terraform import` is the only real solution. 

The way terraform (and by extension, Oracle Resource Manager) works is by keeping track of the resources that are created by terraform in a state file. So even if you have compute instances, they are not tracked by this state file. `terrafrom import` imports existing resources in to the state file, which will then trigger an update to install the `cloud-init` script. 

The fundamental question here seem to be "Can I install the MuShop application on my compute instance ?". The answer to that is yes - just take a look at how these files to see the installation process:
- [Dockerfile](https://github.com/oracle-quickstart/oci-cloudnative/blob/master/deploy/basic/Dockerfile)  how the app is built
- [init script](https://github.com/oracle-quickstart/oci-cloudnative/blob/master/deploy/basic/terraform/scripts/node.sh) shows the processes that install and initialize the application. The object storage related code is not requited since you can `scp` those files directly on to your compute instance.


Overall, I feel this is an edge case given that the goal of the basic stack is to demonstrate infrastructure as code, and this case the infrastructure seems to be created manually.

**Comment by jeevanjoseph** [comment]
Bump - @narendratreddi can you clarify the request ?

**Comment by jeevanjoseph** [comment]
Closing - @narendratreddi please re-open to resume the discussion
