### ISSUE TITLE
Error in installing mushop setup using helm

### ISSUE THREAD

**Issue by aojah1** [oracle-quickstart/oci-cloudnative#67]
helm install mushop-setup setup \
>   --namespace mushop-setup
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ClusterRole): missing required field "rules" in io.k8s.api.rbac.v1beta1.ClusterRole

**Comment by mvandervliet** [comment]
Thanks @aojah1. Can you please share the output of the following for your environment?

```
kubectl version
```

```
helm version
```

**Comment by aojah1** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.5-6+2d6d607cc2dd26", GitCommit:"2d6d607cc2dd26104fd338e0e0646ca3e68333b5", GitTreeState:"clean", BuildDate:"2019-09-24T23:30:21Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

============
helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

**Comment by mvandervliet** [comment]
Ok, thank you. The umbrella (`setup`) chart hasn't been tested with the latest version of the `kubectl` client yet, and perhaps there are some new validations creating this error. But, essentially the `setup` chart simply installs [supporting 3rd party](https://oracle-quickstart.github.io/oci-cloudnative/#setup) helm charts, which aren't absolutely required to deploy the _application_ (`mushop`) chart.

Since the problems are occurring within those 3rd party charts, we will need to update those dependencies once new, compatible versions become available. Or you could downgrade the `kubectl` to an earlier version. Otherwise you can begin with [these instructions](https://oracle-quickstart.github.io/oci-cloudnative/#deploy-mushop), and deploy the application without those optional 3rd party charts

**Comment by aojah1** [comment]
Just to run the Mock Mushop, I guess I will need the chart for Nginx Ingress. Should I just install it independently ?
Nginx Ingress | Ingress controller and public Load Balancer
-- | --

**Comment by aojah1** [comment]
Basically I am not able to execute the following steps after I successfully installed Mushop.

Open a browser with the EXTERNAL-IP created during setup, OR port-forward directly to the edge service resource:

kubectl port-forward \
  --namespace mushop \
  svc/edge 8000:80
Using port-forward connecting localhost:8000 to the edge service

kubectl get svc mushop-setup-nginx-ingress-controller \
  --namespace mushop-setup
Locating EXTERNAL-IP for Ingress Controller. NOTE this will be localhost on local clusters.

**Comment by peterj** [comment]
@aojah1 when you say "not able to execute" - are you getting any errors? What's the output of `kubectl get svc,po -A`?
